#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'aes_core_0', class 'aes_core'
 * The macros are prefixed with 'AES_CORE_0_'.
 * The prefix is the slave descriptor.
 */
#define AES_CORE_0_COMPONENT_TYPE aes_core
#define AES_CORE_0_COMPONENT_NAME aes_core_0
#define AES_CORE_0_BASE 0x0
#define AES_CORE_0_SPAN 64
#define AES_CORE_0_END 0x3f

/*
 * Macros for device 'ILC', class 'interrupt_latency_counter'
 * The macros are prefixed with 'ILC_'.
 * The prefix is the slave descriptor.
 */
#define ILC_COMPONENT_TYPE interrupt_latency_counter
#define ILC_COMPONENT_NAME ILC
#define ILC_BASE 0x0
#define ILC_SPAN 256
#define ILC_END 0xff

/*
 * Macros for device 'video_dma_controller', class 'altera_up_avalon_video_dma_controller'
 * The macros are prefixed with 'VIDEO_DMA_CONTROLLER_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_DMA_CONTROLLER_COMPONENT_TYPE altera_up_avalon_video_dma_controller
#define VIDEO_DMA_CONTROLLER_COMPONENT_NAME video_dma_controller
#define VIDEO_DMA_CONTROLLER_BASE 0x40
#define VIDEO_DMA_CONTROLLER_SPAN 16
#define VIDEO_DMA_CONTROLLER_END 0x4f

/*
 * Macros for device 'audio_and_video_config', class 'altera_up_avalon_audio_and_video_config'
 * The macros are prefixed with 'AUDIO_AND_VIDEO_CONFIG_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_AND_VIDEO_CONFIG_COMPONENT_TYPE altera_up_avalon_audio_and_video_config
#define AUDIO_AND_VIDEO_CONFIG_COMPONENT_NAME audio_and_video_config
#define AUDIO_AND_VIDEO_CONFIG_BASE 0x50
#define AUDIO_AND_VIDEO_CONFIG_SPAN 16
#define AUDIO_AND_VIDEO_CONFIG_END 0x5f

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x100
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x10f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 10
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x110
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x11f
#define DIPSW_PIO_IRQ 2
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 10
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x120
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x12f
#define BUTTON_PIO_IRQ 1
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x130
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x137
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1622665034

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 0
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'onchip_memory_video', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY_VIDEO_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY_VIDEO_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_VIDEO_COMPONENT_NAME onchip_memory_video
#define ONCHIP_MEMORY_VIDEO_BASE 0x100000
#define ONCHIP_MEMORY_VIDEO_SPAN 460802
#define ONCHIP_MEMORY_VIDEO_END 0x170801
#define ONCHIP_MEMORY_VIDEO_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_VIDEO_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_VIDEO_CONTENTS_INFO ""
#define ONCHIP_MEMORY_VIDEO_DUAL_PORT 1
#define ONCHIP_MEMORY_VIDEO_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_VIDEO_INIT_CONTENTS_FILE soc_system_onchip_memory_video
#define ONCHIP_MEMORY_VIDEO_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_VIDEO_INSTANCE_ID NONE
#define ONCHIP_MEMORY_VIDEO_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_VIDEO_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_VIDEO_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY_VIDEO_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_VIDEO_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_VIDEO_SIZE_VALUE 460802
#define ONCHIP_MEMORY_VIDEO_WRITABLE 1
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_MEM_INIT_DATA_WIDTH 1024
#define ONCHIP_MEMORY_VIDEO_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory_video


#endif /* _ALTERA_HPS_0_H_ */
